application: ff2disqus
version: 2
runtime: python
api_version: 1

handlers:

- url: /
  static_files: static/down.html
  upload: static/down.html
  secure: always

- url: /secret
  static_files: static/index.html
  upload: static/index.html
  secure: always

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /static
  static_dir: static

- url: /admin/.*
  script: admin.py
  login: admin

- url: .*
  script: main.py
  secure: always